name: Cyclic Imports
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

jobs:
  cyclic-import:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install packages
        run: |
          poetry run make config-poetry
          poetry run make install-all

      - name: Show installed packages
        run: |
          poetry run poetry show
          poetry run poetry show --tree

      - name: check flamme.analyzer
        run: |
          poetry run python -c "from flamme import analyzer"
      - name: check flamme.ingestor
        run: |
          poetry run python -c "from flamme import ingestor"
      - name: check flamme.reporter
        run: |
          poetry run python -c "from flamme import reporter"
      - name: check flamme.section
        run: |
          poetry run python -c "from flamme import section"
      - name: check flamme.transformer
        run: |
          poetry run python -c "from flamme import transformer"
      - name: check flamme.transformer.df
        run: |
          poetry run python -c "from flamme.transformer import df"
      - name: check flamme.transformer.series
        run: |
          poetry run python -c "from flamme.transformer import series"
      - name: check flamme.utils
        run: |
          poetry run python -c "from flamme import utils"
