name: Cyclic Imports
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

jobs:
  cyclic-import:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.11' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install packages
        run: |
          poetry run make config-poetry
          poetry run make install-all

      - name: Show installed packages
        run: |
          poetry run poetry show
          poetry run poetry show --tree

      - name: check flamme.analyzer
        run: |
          poetry run python -c "from flamme import analyzer"
      - name: check flamme.ingestor
        run: |
          poetry run python -c "from flamme import ingestor"
      - name: check flamme.preprocessor
        run: |
          poetry run python -c "from flamme import preprocessor"
      - name: check flamme.reporter
        run: |
          poetry run python -c "from flamme import reporter"
      - name: check flamme.section
        run: |
          poetry run python -c "from flamme import section"
      - name: check flamme.utils
        run: |
          poetry run python -c "from flamme import utils"
