name: Nightly Package Tests
on:
  schedule:
    - cron: '50 11 * * *' # run at 11:50 AM UTC
  workflow_dispatch:  # to trigger manually

jobs:
  cyclic-imports:
    uses: ./.github/workflows/cyclic-imports.yaml

  stable-all:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, macos-latest, macos-14, macos-13, macos-12 ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          pip install "flamme[all]"

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  stable-min:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, macos-latest, macos-14, macos-13, macos-12 ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          pip install flamme

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  latest-all:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, macos-latest, macos-14, macos-13, macos-12 ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          pip install --pre "flamme[all]"

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  latest-min:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, macos-latest, macos-14, macos-13, macos-12 ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          pip install --pre flamme

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  coola:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        coola-version: [ 0.7.2 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flamme
        run: |
          pip install flamme coola==${{ matrix.coola-version }}

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  grizz:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        grizz-version: [ 0.0.5a0 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flamme
        run: |
          pip install flamme grizz==${{ matrix.grizz-version }}

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  iden:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        iden-version: [ 0.0.4 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flamme
        run: |
          pip install flamme iden==${{ matrix.iden-version }}

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  jinja2:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        jinja2-version: [ 3.1.4, 3.0.3 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flamme
        run: |
          pip install flamme jinja2==${{ matrix.jinja2-version }}

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  matplotlib:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        matplotlib-version: [ 3.9.1, 3.8.4, 3.7.4, 3.6.3 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flamme
        run: |
          pip install flamme feu
          python -c "from feu import install_package; install_package('matplotlib', '${{ matrix.matplotlib-version }}')"

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  numpy:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        numpy-version: [ 2.0.0, 1.26.4, 1.25.2, 1.24.3, 1.23.5 ]
        exclude:
          - numpy-version: 1.23.5
            python-version: '3.12'
          - numpy-version: 1.24.3
            python-version: '3.12'
          - numpy-version: 1.25.2
            python-version: '3.12'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flamme
        run: |
          pip install flamme numpy==${{ matrix.numpy-version }}

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  objectory:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        objectory-version: [ 0.1.2 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flamme
        run: |
          pip install flamme objectory==${{ matrix.objectory-version }}

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  polars:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        polars-version: [ 1.2.0, 1.0.0 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flamme
        run: |
          pip install flamme polars==${{ matrix.polars-version }}

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  pyarrow:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        pyarrow-version: [ 16.1.0, 15.0.2, 14.0.2, 13.0.0, 12.0.1, 11.0.0, 10.0.1 ]
        exclude:
          - pyarrow-version: 13.0.0
            python-version: '3.12'
          - pyarrow-version: 12.0.1
            python-version: '3.12'
          - pyarrow-version: 11.0.0
            python-version: '3.12'
          - pyarrow-version: 10.0.1
            python-version: '3.12'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flamme
        run: |
          pip install flamme feu
          python -c "from feu import install_package; install_package('pyarrow', '${{ matrix.pyarrow-version }}')"

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  scipy:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        scipy-version: [ 1.14.0, 1.13.1, 1.12.0, 1.11.4, 1.10.1 ]
        exclude:
          - scipy-version: 1.14.0
            python-version: '3.9'
          - scipy-version: 1.10.1
            python-version: '3.12'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flamme
        run: |
          pip install flamme scipy==${{ matrix.scipy-version }}

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  #################################
  #     Optional dependencies     #
  #################################


  clickhouse-connect:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        clickhouse-connect-version: [ 0.7.16, 0.7.0 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flamme
        run: |
          pip install flamme clickhouse-connect==${{ matrix.clickhouse-connect-version }}

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  colorlog:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        colorlog-version: [ '6.8', '6.7' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flamme
        run: |
          pip install flamme colorlog==${{ matrix.colorlog-version }}

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  hya:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        hya-version: [ 0.2.3 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flamme
        run: |
          pip install flamme hya==${{ matrix.hya-version }}

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  markdown:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        markdown-version: [ 3.6.0, 3.5.1, 3.4.3 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flamme
        run: |
          pip install flamme markdown==${{ matrix.markdown-version }}

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo


  tqdm:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12', '3.11', '3.10', '3.9' ]
        tqdm-version: [ '4.66.4', '4.65.2' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flamme
        run: |
          pip install flamme tqdm==${{ matrix.tqdm-version }}

      - name: Run some checks
        run: |
          python tests/package_checks.py

      - name: Run demo script
        run: |
          python -m scripts.demo
